services:
  - type: web
    name: ecotasks
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 120
    envVars:
      - key: CLE_SECRETE
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
